saleor/saleor/dashboard/menu/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.menu_list, name='menu-list'),
    url(r'^add/$',
        views.menu_create, name='menu-add'),
    url(r'^(?P<pk>[0-9]+)/edit/$',
        views.menu_edit, name='menu-edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.menu_delete, name='menu-delete'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.menu_details, name='menu-details'),

    url(r'^(?P<menu_pk>[0-9]+)/add/$',
        views.menu_item_create, name='menu-item-add'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/add/$',
        views.menu_item_create, name='menu-item-add'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/edit/$',
        views.menu_item_edit, name='menu-item-edit'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/delete/$',
        views.menu_item_delete, name='menu-item-delete'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/$',
        views.menu_item_details, name='menu-item-details'),

    url(r'^(?P<menu_pk>[0-9]+)/items/reorder/$',
        views.ajax_reorder_menu_items, name='menu-items-reorder'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/items/reorder/$',
        views.ajax_reorder_menu_items, name='menu-items-reorder'),
    url(r'^ajax/links/$',
        views.ajax_menu_links, name='ajax-menu-links')]

saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import (
    cart_urlpatterns as cart_urls, checkout_urlpatterns as checkout_urls)
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.file_upload.views import FileUploadGraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = 'saleor.core.views.handle_404'

non_translatable_urlpatterns = [
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql/', csrf_exempt(FileUploadGraphQLView.as_view(
        schema=schema, graphiql=settings.DEBUG)), name='api'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/$', set_language, name='set_language'),
    url('', include('social_django.urls', namespace='social'))]

translatable_urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^page/', include((page_urls, 'page'), namespace='page')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'', include('payments.urls'))]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(
    *translatable_urlpatterns)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        # static files (images, css, javascript, etc.)
        url(r'^static/(?P<path>.*)$', serve)] + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [
        url(r'^silk/', include('silk.urls', namespace='silk'))]

saleor/templates/dashboard/menu/item/modal/confirm_delete.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}

{% block form_class %}{% endblock %}

{% block action_url %}
{% url "dashboard:menu-item-delete" menu_pk=menu_item.menu.pk item_pk=menu_item.pk %}
{% endblock %}

{% block title %}
{% blocktrans trimmed with menu=menu context "Remove menu item modal title" %}
  Remove menu item {{ menu_item }}
{% endblocktrans %}
{% endblock %}

{% block content %}
  <div class="col s12">
    {% blocktrans trimmed with menu_item=menu_item menu=menu_item.menu context "Remove menu item modal title" %}
      Are you sure you want to remove menu item <strong>{{ menu_item }}</strong> from {{ menu }} menu?
    {% endblocktrans %}
    {% if descendants %}
      <p>
        {% trans "The following menu items will be removed:" context "Remove menu modal text about descendant menu items" %}
        <ul>
          {{ descendants|join:", " }}
        </ul>
      </p>
    {% endif %}
  </div>
{% endblock %}

{% block primary_action %}
{% trans "Remove" context "Dashboard delete action" %}
{% endblock %}